# Generated by Django 5.1.15 on 2026-03-16 13:26

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_device_token'),
        ('encounters', '0003_alter_encounter_input_method_alter_encounter_status'),
        ('notes', '0003_alter_clinicalnote_note_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ehr_system', models.CharField(choices=[('athenahealth', 'athenahealth'), ('eclinicalworks', 'eClinicalWorks'), ('epic', 'Epic'), ('cerner', 'Cerner'), ('nextgen', 'NextGen'), ('other', 'Other')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('fhir_base_url', models.URLField(max_length=500)),
                ('client_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('auth_type', models.CharField(choices=[('client_credentials', 'Client Credentials'), ('authorization_code', 'Authorization Code (SMART)'), ('backend_service', 'Backend Service')], default='client_credentials', max_length=30)),
                ('scopes', models.TextField(blank=True, default='')),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('smart_authorize_url', models.URLField(blank=True, default='', max_length=500)),
                ('smart_token_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.CharField(default='disconnected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_connections', to='accounts.practice')),
            ],
            options={
                'db_table': 'fhir_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRPushLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('fhir_resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=10)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_push_logs', to='notes.clinicalnote')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='fhir.fhirconnection')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_push_logs', to='encounters.encounter')),
            ],
            options={
                'db_table': 'fhir_push_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
