PRIMARY_CARE_TEMPLATES = [
    {
        "name": "Primary Care - Annual Physical",
        "description": "Comprehensive annual wellness exam template with preventive screening checklist",
        "specialty": "primary_care",
        "note_type": "soap",
        "tags": ["annual-physical", "wellness", "preventive"],
        "schema": {
            "sections": [
                {
                    "key": "subjective",
                    "label": "Subjective",
                    "fields": [
                        {"key": "chief_complaint", "label": "Chief Complaint", "type": "text", "required": True},
                        {"key": "hpi", "label": "History of Present Illness", "type": "textarea", "required": True,
                         "ai_prompt": "Generate HPI based on chief complaint and patient demographics"},
                        {"key": "pmh", "label": "Past Medical History", "type": "textarea", "required": False},
                        {"key": "medications", "label": "Current Medications", "type": "textarea", "required": False},
                        {"key": "allergies", "label": "Allergies", "type": "textarea", "required": False},
                        {"key": "family_history", "label": "Family History", "type": "textarea", "required": False},
                        {"key": "social_history", "label": "Social History", "type": "textarea", "required": False},
                        {"key": "ros", "label": "Review of Systems", "type": "checklist",
                         "options": ["Constitutional", "HEENT", "Cardiovascular", "Respiratory",
                                     "Gastrointestinal", "Genitourinary", "Musculoskeletal",
                                     "Integumentary", "Neurological", "Psychiatric", "Endocrine",
                                     "Hematologic/Lymphatic", "Allergic/Immunologic"],
                         "required": True},
                    ],
                },
                {
                    "key": "objective",
                    "label": "Objective",
                    "fields": [
                        {"key": "vitals", "label": "Vital Signs", "type": "structured",
                         "subfields": [
                             {"key": "bp", "label": "BP", "type": "text", "placeholder": "120/80"},
                             {"key": "hr", "label": "HR", "type": "text", "placeholder": "72"},
                             {"key": "temp", "label": "Temp", "type": "text", "placeholder": "98.6"},
                             {"key": "rr", "label": "RR", "type": "text", "placeholder": "16"},
                             {"key": "spo2", "label": "SpO2", "type": "text", "placeholder": "98%"},
                             {"key": "weight", "label": "Weight", "type": "text"},
                             {"key": "height", "label": "Height", "type": "text"},
                             {"key": "bmi", "label": "BMI", "type": "text"},
                         ]},
                        {"key": "physical_exam", "label": "Physical Examination", "type": "textarea", "required": True,
                         "ai_prompt": "Generate physical exam findings based on chief complaint"},
                    ],
                },
                {
                    "key": "assessment",
                    "label": "Assessment",
                    "fields": [
                        {"key": "diagnoses", "label": "Diagnoses", "type": "textarea", "required": True,
                         "ai_prompt": "Suggest assessment based on subjective and objective findings"},
                        {"key": "icd10", "label": "ICD-10 Codes", "type": "code_list"},
                    ],
                },
                {
                    "key": "plan",
                    "label": "Plan",
                    "fields": [
                        {"key": "treatment", "label": "Treatment Plan", "type": "textarea", "required": True},
                        {"key": "prescriptions", "label": "Prescriptions", "type": "textarea"},
                        {"key": "follow_up", "label": "Follow-up", "type": "text"},
                        {"key": "referrals", "label": "Referrals", "type": "textarea"},
                        {"key": "preventive_screening", "label": "Preventive Screening", "type": "checklist",
                         "options": ["Lipid Panel", "A1c", "Mammogram", "Colonoscopy",
                                     "Bone Density", "Vision Screening", "Depression Screening (PHQ-9)",
                                     "Immunizations Review"]},
                        {"key": "cpt", "label": "CPT Codes", "type": "code_list"},
                    ],
                },
            ],
            "ai_instructions": "Focus on comprehensive documentation. Include screening recommendations based on age and sex. Ensure all preventive care elements are addressed for annual visit documentation.",
        },
    },
    {
        "name": "Primary Care - Acute Visit",
        "description": "Template for acute/urgent care visits in primary care setting",
        "specialty": "primary_care",
        "note_type": "soap",
        "tags": ["acute", "urgent", "sick-visit"],
        "schema": {
            "sections": [
                {
                    "key": "subjective",
                    "label": "Subjective",
                    "fields": [
                        {"key": "chief_complaint", "label": "Chief Complaint", "type": "text", "required": True},
                        {"key": "hpi", "label": "HPI", "type": "textarea", "required": True,
                         "ai_prompt": "Generate focused HPI for acute visit"},
                        {"key": "associated_symptoms", "label": "Associated Symptoms", "type": "textarea"},
                        {"key": "medications_tried", "label": "Medications/Treatments Tried", "type": "textarea"},
                    ],
                },
                {
                    "key": "objective",
                    "label": "Objective",
                    "fields": [
                        {"key": "vitals", "label": "Vital Signs", "type": "structured",
                         "subfields": [
                             {"key": "bp", "label": "BP", "type": "text"},
                             {"key": "hr", "label": "HR", "type": "text"},
                             {"key": "temp", "label": "Temp", "type": "text"},
                             {"key": "rr", "label": "RR", "type": "text"},
                             {"key": "spo2", "label": "SpO2", "type": "text"},
                         ]},
                        {"key": "focused_exam", "label": "Focused Physical Examination", "type": "textarea",
                         "required": True},
                    ],
                },
                {
                    "key": "assessment",
                    "label": "Assessment",
                    "fields": [
                        {"key": "diagnoses", "label": "Assessment/Diagnoses", "type": "textarea", "required": True},
                        {"key": "differential", "label": "Differential Diagnosis", "type": "textarea"},
                    ],
                },
                {
                    "key": "plan",
                    "label": "Plan",
                    "fields": [
                        {"key": "treatment", "label": "Treatment", "type": "textarea", "required": True},
                        {"key": "prescriptions", "label": "Prescriptions", "type": "textarea"},
                        {"key": "follow_up", "label": "Follow-up Instructions", "type": "text"},
                        {"key": "return_precautions", "label": "Return Precautions", "type": "textarea"},
                    ],
                },
            ],
            "ai_instructions": "Focus on the acute complaint. Generate concise, focused documentation. Include relevant differential diagnoses.",
        },
    },
]

DERMATOLOGY_TEMPLATES = [
    {
        "name": "Dermatology - Skin Lesion Evaluation",
        "description": "Comprehensive dermatology template for skin lesion assessment with ABCDE criteria",
        "specialty": "dermatology",
        "note_type": "soap",
        "tags": ["skin-lesion", "biopsy", "mole-check"],
        "schema": {
            "sections": [
                {
                    "key": "subjective",
                    "label": "Subjective",
                    "fields": [
                        {"key": "chief_complaint", "label": "Chief Complaint", "type": "text", "required": True},
                        {"key": "hpi", "label": "HPI", "type": "textarea", "required": True,
                         "ai_prompt": "Generate dermatology-focused HPI including onset, duration, changes, symptoms (itching, bleeding, pain)"},
                        {"key": "lesion_history", "label": "Lesion History", "type": "textarea",
                         "placeholder": "Duration, changes in size/color/shape, prior treatments"},
                        {"key": "skin_cancer_risk", "label": "Skin Cancer Risk Factors", "type": "checklist",
                         "options": ["Fair skin", "History of sunburns", "Family history melanoma",
                                     "Personal history skin cancer", "Immunosuppression",
                                     "Multiple dysplastic nevi", "Organ transplant"]},
                        {"key": "medications", "label": "Current Medications", "type": "textarea"},
                    ],
                },
                {
                    "key": "objective",
                    "label": "Objective",
                    "fields": [
                        {"key": "lesion_description", "label": "Lesion Description", "type": "textarea",
                         "required": True,
                         "ai_prompt": "Generate dermatological lesion description using standard morphology terminology"},
                        {"key": "abcde", "label": "ABCDE Criteria", "type": "structured",
                         "subfields": [
                             {"key": "asymmetry", "label": "Asymmetry", "type": "select",
                              "options": ["Symmetric", "Asymmetric"]},
                             {"key": "border", "label": "Border", "type": "select",
                              "options": ["Regular", "Irregular", "Scalloped", "Poorly defined"]},
                             {"key": "color", "label": "Color", "type": "text",
                              "placeholder": "Uniform tan, variegated brown/black..."},
                             {"key": "diameter", "label": "Diameter", "type": "text",
                              "placeholder": "mm"},
                             {"key": "evolution", "label": "Evolution", "type": "select",
                              "options": ["Stable", "Changing", "New lesion"]},
                         ]},
                        {"key": "location", "label": "Location", "type": "text", "required": True},
                        {"key": "size", "label": "Size (cm)", "type": "text"},
                        {"key": "dermoscopy", "label": "Dermoscopy Findings", "type": "textarea"},
                        {"key": "photos", "label": "Clinical Photos", "type": "text",
                         "placeholder": "Number of photos taken and stored"},
                    ],
                },
                {
                    "key": "assessment",
                    "label": "Assessment",
                    "fields": [
                        {"key": "diagnoses", "label": "Clinical Impression", "type": "textarea", "required": True},
                        {"key": "differential", "label": "Differential Diagnosis", "type": "textarea"},
                    ],
                },
                {
                    "key": "plan",
                    "label": "Plan",
                    "fields": [
                        {"key": "procedure", "label": "Procedure", "type": "textarea",
                         "placeholder": "Biopsy type (shave/punch/excisional), anesthesia, site prep"},
                        {"key": "treatment", "label": "Treatment Plan", "type": "textarea", "required": True},
                        {"key": "prescriptions", "label": "Prescriptions", "type": "textarea"},
                        {"key": "wound_care", "label": "Wound Care Instructions", "type": "textarea"},
                        {"key": "follow_up", "label": "Follow-up", "type": "text"},
                        {"key": "pathology_pending", "label": "Pathology Pending", "type": "select",
                         "options": ["Yes", "No", "N/A"]},
                    ],
                },
            ],
            "ai_instructions": "Use precise dermatological morphology terminology (papule, plaque, macule, etc.). Include ABCDE criteria assessment for pigmented lesions. Document photographic evidence references.",
        },
    },
]

PSYCHIATRY_TEMPLATES = [
    {
        "name": "Psychiatry - Initial Psychiatric Evaluation",
        "description": "Comprehensive initial psychiatric assessment template with PHQ-9, GAD-7 scoring",
        "specialty": "psychiatry",
        "note_type": "soap",
        "tags": ["initial-eval", "psychiatric-assessment", "mental-health"],
        "schema": {
            "sections": [
                {
                    "key": "subjective",
                    "label": "Subjective",
                    "fields": [
                        {"key": "chief_complaint", "label": "Chief Complaint / Reason for Visit", "type": "text",
                         "required": True},
                        {"key": "hpi", "label": "History of Present Illness", "type": "textarea", "required": True,
                         "ai_prompt": "Generate psychiatric HPI including onset, duration, severity, triggers, current symptoms, functional impact"},
                        {"key": "psychiatric_history", "label": "Past Psychiatric History", "type": "textarea",
                         "placeholder": "Prior diagnoses, hospitalizations, past medications and response, suicide attempts"},
                        {"key": "substance_use", "label": "Substance Use History", "type": "textarea",
                         "placeholder": "Alcohol, tobacco, cannabis, other substances - frequency, quantity, last use"},
                        {"key": "trauma_history", "label": "Trauma History", "type": "textarea"},
                        {"key": "family_psychiatric", "label": "Family Psychiatric History", "type": "textarea"},
                        {"key": "social_history", "label": "Social History", "type": "textarea",
                         "placeholder": "Living situation, employment, relationships, support system, legal issues"},
                        {"key": "current_medications", "label": "Current Medications", "type": "textarea"},
                        {"key": "allergies", "label": "Allergies", "type": "textarea"},
                    ],
                },
                {
                    "key": "objective",
                    "label": "Objective / Mental Status Examination",
                    "fields": [
                        {"key": "appearance", "label": "Appearance", "type": "textarea",
                         "placeholder": "Age-appropriate, grooming, attire, psychomotor activity"},
                        {"key": "behavior", "label": "Behavior", "type": "textarea",
                         "placeholder": "Cooperative, eye contact, rapport"},
                        {"key": "speech", "label": "Speech", "type": "textarea",
                         "placeholder": "Rate, rhythm, volume, tone"},
                        {"key": "mood", "label": "Mood (Patient-reported)", "type": "text"},
                        {"key": "affect", "label": "Affect (Observed)", "type": "text",
                         "placeholder": "Range, congruence, stability"},
                        {"key": "thought_process", "label": "Thought Process", "type": "text",
                         "placeholder": "Linear, goal-directed, tangential, circumstantial"},
                        {"key": "thought_content", "label": "Thought Content", "type": "textarea",
                         "placeholder": "Delusions, obsessions, phobias, ideas of reference"},
                        {"key": "perceptions", "label": "Perceptions", "type": "textarea",
                         "placeholder": "Hallucinations (AH, VH), illusions"},
                        {"key": "cognition", "label": "Cognition", "type": "textarea",
                         "placeholder": "Alert, oriented, attention, concentration, memory"},
                        {"key": "insight", "label": "Insight", "type": "select",
                         "options": ["Good", "Fair", "Limited", "Poor"]},
                        {"key": "judgment", "label": "Judgment", "type": "select",
                         "options": ["Good", "Fair", "Limited", "Poor"]},
                        {"key": "suicidal_ideation", "label": "Suicidal Ideation", "type": "textarea",
                         "required": True,
                         "placeholder": "Denies SI/HI. If present: frequency, plan, intent, means, protective factors"},
                        {"key": "homicidal_ideation", "label": "Homicidal Ideation", "type": "textarea",
                         "required": True},
                        {"key": "phq9_score", "label": "PHQ-9 Score", "type": "text"},
                        {"key": "gad7_score", "label": "GAD-7 Score", "type": "text"},
                    ],
                },
                {
                    "key": "assessment",
                    "label": "Assessment",
                    "fields": [
                        {"key": "diagnoses", "label": "Diagnoses (DSM-5)", "type": "textarea", "required": True},
                        {"key": "risk_assessment", "label": "Risk Assessment", "type": "textarea", "required": True,
                         "placeholder": "Risk level (low/moderate/high), risk factors, protective factors"},
                    ],
                },
                {
                    "key": "plan",
                    "label": "Plan",
                    "fields": [
                        {"key": "medication_plan", "label": "Medication Plan", "type": "textarea"},
                        {"key": "therapy_recommendations", "label": "Therapy Recommendations", "type": "textarea"},
                        {"key": "safety_plan", "label": "Safety Plan", "type": "textarea",
                         "conditional": {"show_if": {"field": "suicidal_ideation", "not_empty": True}}},
                        {"key": "follow_up", "label": "Follow-up", "type": "text", "required": True},
                        {"key": "crisis_resources", "label": "Crisis Resources Provided", "type": "select",
                         "options": ["Yes", "No", "N/A"]},
                    ],
                },
            ],
            "ai_instructions": "Use psychiatric terminology accurately. Always document suicide/homicide risk assessment. Include PHQ-9 and GAD-7 scores when available. Follow DSM-5 diagnostic criteria in assessment. Ensure safety planning is documented when appropriate.",
        },
    },
]

ALL_SPECIALTY_TEMPLATES = PRIMARY_CARE_TEMPLATES + DERMATOLOGY_TEMPLATES + PSYCHIATRY_TEMPLATES
