# Generated by Django 5.1.15 on 2026-03-16 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_encounter_template_used'),
        ('notes', '0002_alter_clinicalnote_cpt_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('completeness', 'Completeness'), ('billing', 'Billing Optimization'), ('compliance', 'CMS Compliance'), ('coding', 'Code Validation')], default='completeness', max_length=20)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=10)),
                ('points', models.IntegerField(default=10, help_text='Points deducted when this rule fails')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quality_rules',
                'ordering': ['category', 'rule_code'],
            },
        ),
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0)),
                ('completeness_score', models.IntegerField(default=0)),
                ('billing_score', models.IntegerField(default=0)),
                ('compliance_score', models.IntegerField(default=0)),
                ('suggested_em_level', models.CharField(blank=True, default='', max_length=10)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='notes.clinicalnote')),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_score', to='encounters.encounter')),
            ],
            options={
                'db_table': 'quality_scores',
            },
        ),
        migrations.CreateModel(
            name='QualityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='quality.qualityrule')),
                ('quality_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='quality.qualityscore')),
            ],
            options={
                'db_table': 'quality_findings',
                'ordering': ['-created_at'],
            },
        ),
    ]
