# Generated by Django 5.1.15 on 2026-03-16 02:56

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_en', encrypted_model_fields.fields.EncryptedTextField()),
                ('summary_es', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('reading_level', models.CharField(choices=[('grade_5', 'Grade 5'), ('grade_8', 'Grade 8'), ('grade_12', 'Grade 12')], default='grade_8', max_length=10)),
                ('medical_terms_explained', models.JSONField(default=list)),
                ('disclaimer_text', models.TextField(default='This summary is for informational purposes only and does not constitute medical advice.')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('app', 'App'), ('widget', 'Widget'), ('sms_link', 'SMS Link'), ('email_link', 'Email Link')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='notes.clinicalnote')),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_summary', to='encounters.encounter')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_summaries', to='notes.promptversion')),
            ],
            options={
                'verbose_name_plural': 'Patient summaries',
                'db_table': 'patient_summaries',
            },
        ),
    ]
