# Generated by Django 5.1.15 on 2026-03-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsummary',
            name='medical_terms_explained',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
