# Generated by Django 5.1.15 on 2026-03-20 12:10

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_alter_patientsummary_medical_terms_explained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsummary',
            name='medical_terms_explained',
            field=apps.core.fields.EncryptedJSONField(blank=True, default=list),
        ),
    ]
