# Generated by Django 5.1.15 on 2026-03-16 02:56

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_date', models.DateField()),
                ('input_method', models.CharField(choices=[('recording', 'Recording'), ('paste', 'Paste'), ('dictation', 'Dictation'), ('scan', 'Scan')], max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('transcribing', 'Transcribing'), ('generating_note', 'Generating Note'), ('generating_summary', 'Generating Summary'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('transcription_failed', 'Transcription Failed'), ('note_generation_failed', 'Note Generation Failed'), ('summary_generation_failed', 'Summary Generation Failed')], default='uploading', max_length=30)),
                ('consent_recording', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_method', models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('digital_checkbox', 'Digital Checkbox'), ('written', 'Written')], default='', max_length=20)),
                ('consent_jurisdiction_state', models.CharField(blank=True, default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patients.patient')),
            ],
            options={
                'db_table': 'encounters',
                'ordering': ['-encounter_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_url', encrypted_model_fields.fields.EncryptedCharField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('format', models.CharField(choices=[('wav', 'WAV'), ('mp3', 'MP3'), ('webm', 'WebM')], max_length=10)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='encounters.encounter')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', encrypted_model_fields.fields.EncryptedTextField()),
                ('speaker_segments', models.JSONField(default=list)),
                ('medical_terms_detected', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('language_detected', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='encounters.encounter')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
    ]
