# Generated by Django 5.1.15 on 2026-03-16 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('note_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='note_templates.notetemplate'),
        ),
    ]
