# Generated by Django 5.1.15 on 2026-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_encounter_template_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='input_method',
            field=models.CharField(choices=[('recording', 'Recording'), ('paste', 'Paste'), ('dictation', 'Dictation'), ('scan', 'Scan'), ('telehealth', 'Telehealth')], max_length=20),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('transcribing', 'Transcribing'), ('generating_note', 'Generating Note'), ('generating_summary', 'Generating Summary'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('transcription_failed', 'Transcription Failed'), ('note_generation_failed', 'Note Generation Failed'), ('summary_generation_failed', 'Summary Generation Failed'), ('quality_checking', 'Quality Checking')], default='uploading', max_length=30),
        ),
    ]
