# Generated by Django 5.1.15 on 2026-03-20 12:10

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_encounter_input_method_alter_encounter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='medical_terms_detected',
            field=apps.core.fields.EncryptedJSONField(default=list),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='speaker_segments',
            field=apps.core.fields.EncryptedJSONField(default=list),
        ),
    ]
