# Generated by Django 5.1.15 on 2026-03-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('encounter', 'Encounter'), ('note', 'Note'), ('summary', 'Summary'), ('recording', 'Recording'), ('template', 'Template'), ('quality_score', 'Quality Score')], max_length=20),
        ),
    ]
