# Generated by Django 5.1.15 on 2026-03-20 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_resource_type'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], default='success', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='source_system',
            field=models.CharField(default='api', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('share', 'Share'), ('login_failed', 'Login Failed'), ('break_glass', 'Break Glass'), ('disclose', 'Disclose')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('encounter', 'Encounter'), ('note', 'Note'), ('summary', 'Summary'), ('recording', 'Recording'), ('template', 'Template'), ('quality_score', 'Quality Score'), ('telehealth', 'Telehealth'), ('fhir_push', 'FHIR Push'), ('disclosure', 'Disclosure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BreakGlassAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_glass_approvals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_accesses', to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'break_glass_accesses',
                'ordering': ['-created_at'],
            },
        ),
    ]
