# Generated by Django 5.1.15 on 2026-03-16 02:56

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('last_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('name_search_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('email', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('date_of_birth', encrypted_model_fields.fields.EncryptedDateField()),
                ('language_preference', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.practice')),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
