# Generated by Django 5.1.15 on 2026-03-16 02:56

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(choices=[('soap_note', 'SOAP Note'), ('patient_summary', 'Patient Summary'), ('medical_terms', 'Medical Terms')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('template_text', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_versions',
                'ordering': ['-created_at'],
                'unique_together': {('prompt_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('soap', 'SOAP'), ('free_text', 'Free Text'), ('h_and_p', 'History & Physical')], default='soap', max_length=20)),
                ('subjective', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('objective', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('assessment', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('plan', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('raw_content', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('icd10_codes', models.JSONField(default=list)),
                ('cpt_codes', models.JSONField(default=list)),
                ('ai_generated', models.BooleanField(default=False)),
                ('doctor_edited', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_notes', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='encounters.encounter')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='notes.promptversion')),
            ],
            options={
                'db_table': 'clinical_notes',
            },
        ),
    ]
