# Generated by Django 5.1.15 on 2026-03-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='cpt_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='icd10_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
