# Generated by Django 5.1.15 on 2026-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_clinicalnote_cpt_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='note_type',
            field=models.CharField(choices=[('soap', 'SOAP'), ('free_text', 'Free Text'), ('h_and_p', 'History & Physical'), ('telehealth_soap', 'Telehealth SOAP')], default='soap', max_length=20),
        ),
    ]
