# Generated by Django 5.1.15 on 2026-03-20 12:10

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_clinicalnote_note_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='cpt_codes',
            field=apps.core.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clinicalnote',
            name='icd10_codes',
            field=apps.core.fields.EncryptedJSONField(blank=True, default=list),
        ),
    ]
