# Generated by Django 5.1.15 on 2026-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='llm_provider',
            field=models.CharField(choices=[('claude', 'Claude Only'), ('gemini', 'Gemini Only (Most Affordable)'), ('claude+gemini', 'Claude + Gemini (Best Value)')], default='claude', help_text='AI model provider for note generation and summaries', max_length=20),
        ),
    ]
