# Generated by Django 5.1.15 on 2026-03-16 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_device_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('specialty', models.CharField(choices=[('primary_care', 'Primary Care'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('cardiology', 'Cardiology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology'), ('gastroenterology', 'Gastroenterology'), ('general', 'General')], default='general', max_length=30)),
                ('note_type', models.CharField(choices=[('soap', 'SOAP'), ('free_text', 'Free Text'), ('h_and_p', 'H&P')], default='soap', max_length=20)),
                ('schema', models.JSONField(default=dict)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('practice', 'Practice'), ('public', 'Public (Marketplace)')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('clone_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('parent_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='note_templates.notetemplate')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='accounts.practice')),
            ],
            options={
                'db_table': 'note_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='note_templates.notetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_favorites',
            },
        ),
        migrations.CreateModel(
            name='TemplateRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='note_templates.notetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(fields=['specialty', 'status'], name='note_templa_special_72d87e_idx'),
        ),
        migrations.AddIndex(
            model_name='notetemplate',
            index=models.Index(fields=['visibility', 'status'], name='note_templa_visibil_0a7601_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='templatefavorite',
            unique_together={('template', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='templaterating',
            unique_together={('template', 'user')},
        ),
    ]
