# Generated by Django 5.1.15 on 2026-03-16 13:26

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0003_alter_encounter_input_method_alter_encounter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateComplianceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state_code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('consent_type', models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('written', 'Written'), ('digital', 'Digital/Electronic'), ('none_required', 'Not Required')], default='verbal', max_length=20)),
                ('consent_required', models.BooleanField(default=True)),
                ('consent_statute', models.CharField(blank=True, default='', max_length=255)),
                ('recording_consent', models.CharField(choices=[('one_party', 'One-Party Consent'), ('two_party', 'Two-Party Consent (All-Party)')], default='one_party', max_length=20)),
                ('prescribing_restrictions', models.TextField(blank=True, default='')),
                ('interstate_compact', models.BooleanField(default=False)),
                ('medicaid_coverage', models.BooleanField(default=True)),
                ('additional_rules', models.JSONField(blank=True, default=dict)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'state_compliance_rules',
                'ordering': ['state_code'],
            },
        ),
        migrations.CreateModel(
            name='TelehealthEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_location_state', models.CharField(max_length=2)),
                ('patient_location_city', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('patient_location_setting', models.CharField(choices=[('home', 'Patient Home'), ('office', 'Office/Workplace'), ('facility', 'Healthcare Facility'), ('other', 'Other')], default='home', max_length=20)),
                ('provider_location_state', models.CharField(blank=True, default='', max_length=2)),
                ('provider_location_city', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='')),
                ('modality', models.CharField(choices=[('audio_video', 'Audio + Video'), ('audio_only', 'Audio Only'), ('store_forward', 'Store and Forward')], default='audio_video', max_length=20)),
                ('platform', models.CharField(blank=True, default='', max_length=100)),
                ('consent_type', models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('written', 'Written'), ('digital', 'Digital/Electronic'), ('none_required', 'Not Required')], default='', max_length=20)),
                ('consent_obtained', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_statute', models.CharField(blank=True, default='', max_length=255)),
                ('pos_code', models.CharField(blank=True, choices=[('02', '02 - Telehealth (Facility)'), ('10', '10 - Telehealth (Patient Home)')], default='', max_length=2)),
                ('cpt_modifier', models.CharField(blank=True, choices=[('-95', '-95 (Synchronous Telehealth)'), ('-GT', '-GT (Legacy Telehealth)'), ('-GQ', '-GQ (Asynchronous Telehealth)')], default='', max_length=5)),
                ('technology_adequate', models.BooleanField(default=True)),
                ('technology_notes', models.TextField(blank=True, default='')),
                ('compliance_warnings', models.JSONField(blank=True, default=list)),
                ('prescribing_restrictions_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telehealth', to='encounters.encounter')),
            ],
            options={
                'db_table': 'telehealth_encounters',
            },
        ),
    ]
