# Generated by Django 5.1.15 on 2026-03-20 12:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreachIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed'), ('notified', 'Notified'), ('resolved', 'Resolved')], default='detected', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_patients_count', models.IntegerField(default=0)),
                ('phi_types_involved', models.JSONField(blank=True, default=list)),
                ('notification_deadline', models.DateTimeField(blank=True, null=True)),
                ('hhs_notified_at', models.DateTimeField(blank=True, null=True)),
                ('patients_notified_at', models.DateTimeField(blank=True, null=True)),
                ('remediation_steps', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'breach_incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAssociateAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_type', models.CharField(choices=[('cloud', 'Cloud Provider'), ('ai', 'AI Provider'), ('communication', 'Communication Provider'), ('database', 'Database Provider'), ('analytics', 'Analytics Provider'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('scope_description', models.TextField(blank=True, default='')),
                ('document_s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('document_hash', models.CharField(blank=True, default='', max_length=128)),
                ('breach_notification_hours', models.IntegerField(default=72)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_associate_agreements',
                'ordering': ['-effective_date'],
            },
        ),
    ]
